### ISSUE TITLE
v5.0.15 will case error in react-native ios used in remote-redux-devtools

### ISSUE THREAD

**Issue by feyy** [SocketCluster/socketcluster-client#67] opened 2016-11-01 09:00 UTC
![image](https://cloud.githubusercontent.com/assets/3056002/19884471/d77b79c4-a054-11e6-9ebb-384500cbaa98.png)

**Comment by zalmoxisus** [comment] 2016-11-01 09:24
@jondubois, here's the detailed log: https://github.com/zalmoxisus/remote-redux-devtools/issues/51#issuecomment-257514941

**Comment by jondubois** [comment] 2016-11-01 09:39
@zalmoxisus @feyy Does it work with v5.0.14?

**Comment by jondubois** [comment] 2016-11-01 09:42
This is the only change which was introduced in v5.0.15 https://github.com/SocketCluster/socketcluster-client/commit/6c7f4e17badddb5dbd0710442936c46c1149e3ec

**Comment by jondubois** [comment] 2016-11-01 09:42
I can roll it back if that's the problem.

**Comment by jondubois** [comment] 2016-11-01 09:44
It's strange because we use `global` here https://github.com/SocketCluster/socketcluster-client/blob/master/lib/scsocketcreator.js#L44 but it doesn't seem to cause any problems?

**Comment by zalmoxisus** [comment] 2016-11-01 09:50
@jondubois, I didn't reproduce that. We updated the lib from `socketcluster-client@4` to `@5`, so it's not related to a specific patch version I guess.

**Comment by jondubois** [comment] 2016-11-01 09:58
@zalmoxisus Can you find out which version introduced the problem? It's quite hard to setup react native on my Linux machine so I can't test.

**Comment by zalmoxisus** [comment] 2016-11-01 17:55
@jondubois, I tried earlier versions. It appears only on `5.0.15`. Removing `global.WebSocket || ` from [here](https://github.com/SocketCluster/socketcluster-client/commit/6c7f4e17badddb5dbd0710442936c46c1149e3ec). Strangely, it appears only on iOS, not for Android.

**Comment by sjmueller** [comment] 2016-11-01 20:30
Can also confirm that this breaks react-native, indeed because of 6c7f4e1.

**Comment by jondubois** [comment] 2017-05-24 18:52
@sjmueller @zalmoxisus Do you know if this issue has been resolved in newer versions of socketcluster-client? The logic that was causing problems was changed a while ago:

https://github.com/SocketCluster/socketcluster-client/blob/master/lib/sctransport.js#L7-L17

**Comment by zalmoxisus** [comment] 2017-05-24 19:16
@jondubois the fix is landed on React Native >= 0.43, so the older versions of `socketcluster-client` should work as well.

**Comment by jondubois** [comment] 2017-05-24 19:22
Thanks @zalmoxisus :)

**Closed** 2018-05-16 20:37 UTC
